# Generated by Django 6.0.4 on 2026-04-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the original file for deduplication', max_length=64),
        ),
    ]
