# Generated by Django 6.0.4 on 2026-04-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_tags_and_ai_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="analytics_code",
            field=models.TextField(
                blank=True,
                help_text="Analytics snippet (GA, Gauges, etc.) — pasted into the &lt;head&gt; of every page",
            ),
        ),
    ]
